### ISSUE TITLE
Add support for 8.9.0 LTS

### ISSUE THREAD

**Issue by shahmirn** [GoogleCloudPlatform/cloud-functions-emulator#156] opened 2017-10-31 19:11 UTC
### Description

ShahmirsHundredXMBP:~ shahmirn$ functions start
Warning: You're using Node.js v8.9.0 but Google Cloud Functions only supports v6.11.1.

### Steps to reproduce

Install the latest LTS and run functions start, which results in the warning

Thanks!

**Comment by anfedorov** [comment] 2017-11-12 21:04
This is probably to match what's running on the server, so it's not just the emulator that needs to be updated.

**Comment by jmdobry** [comment] 2017-11-13 21:22
Closing as this currently works as intended.

The emulator is intended to support the version of Node.js used by the production Cloud Functions service. If/when Cloud Functions changes their Node.js version, the Emulator will follow. It's okay if you use a version newer than v6.11.1, the Emulator just prints the warning to inform you that you're using a version different than what production uses.

**Closed by jmdobry** 2017-11-13 21:22 UTC
Labels: question, wontfix

**Comment by shahmirn** [comment] 2017-12-12 17:37
@jmdobry Are there plans to update the Cloud Functions service to use Node 8 LTS? Is there a github issue in some other repo where we can track the progress of that?

**Comment by jmdobry** [comment] 2017-12-12 17:40
https://b.corp.google.com/issues/66770141
