### ISSUE TITLE
Unable to re-deploy a function

### ISSUE THREAD

**Issue by jasonpolites** [GoogleCloudPlatform/cloud-functions-emulator#57] opened 2017-03-05 06:10 UTC
### Description

I am not able to re-deploy an existing function

### Steps to reproduce

```
time functions deploy proxyRequest --trigger-http
ERROR: Function proxyRequest in location us-central1 in project avian-altar-160417 already exists

real	0m14.672s
user	0m12.829s
sys	0m1.111s

```

**Comment by jmdobry** [comment] 2017-03-05 06:29
Duplicate of #48

**Closed by jmdobry** 2017-03-05 06:29 UTC
Labels: duplicate
