### ISSUE TITLE
Local Google Function Trigger by bucket / PubSub topic?

### ISSUE THREAD

**Issue by nagarashish** [GoogleCloudPlatform/cloud-functions-emulator#116] opened 2017-06-11 17:40 UTC
I have a Linux box with public IP.  I am trying to test google function using emulator locally.

How to use  Cloud Storage bucket trigger and Cloud Pub/Sub topic trigger to test google function using emulator locally.

**Comment by jpkleemans** [comment] 2017-06-14 15:49
I have the same issue. When using `--trigger-topic`, how to connect the function to the pubsub emulator?

**Comment by jmdobry** [comment] 2017-06-16 16:31
The Cloud Functions Emulator does not currently support automatic invocation of background functions. The only way to invoke them is using the `call` command. See [Calling Functions](https://github.com/GoogleCloudPlatform/cloud-functions-emulator/wiki/Calling-functions#calling-background-functions).

Duplicate of #28

**Closed by jmdobry** 2017-06-16 16:31 UTC
Labels: duplicate, question

**Comment by alejomendoza** [comment] 2017-09-11 17:06
You should probably add this in the docs @jmdobry
