### ISSUE TITLE
Using emulator's CLI with zsh shell installed

### ISSUE THREAD

**Issue by msjaber** [GoogleCloudPlatform/cloud-functions-emulator#131] opened 2017-08-11 06:12 UTC
### Description

Just wanna tell that you can't use the emulator's `functions` command if you're using `zsh` as your main shell. Since the emulator's `functions` command is in conflict with `zsh`'s `functions`

### Solution

[You can switch the shell back to bash](https://stackoverflow.com/a/10341338) temporarily:

Switch to `bash`:
`exec bash`

Switch back to `zsh`:
`exec zsh
`

Thanks,

**Comment by ApeNox** [comment] 2017-08-14 15:31
zsh is so common these days, poor support from Google calling a global module with the name functions.
Such a generic name, why not gfunctions ?
calling any global command with such a commonly used phrase is bad practice, not like google tbh.
Hopefully the change it sometime soon.

**Comment by jmdobry** [comment] 2017-08-18 17:09
Duplicate of #29.

### Solution

Use `functions-emulator` instead.

Since 1.0.0-alpha.1 the Emulator has shipped with a second alternative binary (`functions-emulator`) to avoid name conflicts with `functions`.

**Closed by jmdobry** 2017-08-18 17:09 UTC
Labels: duplicate
