### ISSUE TITLE
Can't get the emulator to run anything on my Mac

### ISSUE THREAD

**Issue by nagarjun** [GoogleCloudPlatform/cloud-functions-emulator#113] opened 2017-06-06 11:36 UTC
### Description

I just followed the installation instructions on the README and installed the package globally via NPM.

`npm install -g @google-cloud/functions-emulator`

After installation, when I type `functions --help` in my terminal, I get the following error:

```
➜  function-helloWorld functions --help
zsh: bad option: -h

```

I use a Mac running Node v6.10.2 with iTerm and Oh My Zsh. There were no errors during installation. When I type `functions start` or any of the other commands, nothing happens. My terminal just goes to the next line prompting me to input again like this:

```
➜  function-helloWorld functions start
➜  function-helloWorld
```

What am I missing? Not sure if this is a bug or if there's something wrong with the package.

**Comment by jmdobry** [comment] 2017-06-07 18:12
Duplicate of #29 

If you're using ZSH, use `functions-emulator` instead of `functions`.

**Closed by jmdobry** 2017-06-07 18:12 UTC
Labels: duplicate
