### ISSUE TITLE
Conflict with zsh functions command

### ISSUE THREAD

**Issue by zmarkan** [GoogleCloudPlatform/cloud-functions-emulator#112] opened 2017-06-05 05:40 UTC
### Description

ZSH has an built-in feature called functions with a reserved command. Every time `functions` is run that script takes precedence. It works fine on Bash though.

### Steps to reproduce

- install ZSH
- Run it: `/bin/zsh`
- Verify the npm/yarn globals are working correctly , such as: `which firebase` - should give you something like:  `/Users/zan/.nvm/versions/node/v6.10.2/bin/firebase`
- Run `which functions` - it gives you this output: `functions: shell built-in command`

### Suggestion

I've managed to alias this command to `gcfunctions` to avoid the conflict. I suggest the emulator is also remapped to something similar.

Thanks!

**Comment by Binarytales** [comment] 2017-06-05 10:52
This is a duplicate of https://github.com/GoogleCloudPlatform/cloud-functions-emulator/issues/29

Use `$ functions-emulator ...`

**Closed** 2017-06-05 11:19 UTC
